function storeDb() {
  let databaseJakarta = [
    {
      name: "Puskesmas Kecamatan KEPULAUAN SERIBU UTARA",
      area: "Kepulauan Seribu",
      alamat: "Pulau Kelapa",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KEPULAUAN SERIBU UTARA",
      area: "Kepulauan Seribu",
      alamat: "Kec. Kep. Seribu Utara",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KEPULAUAN SERIBU UTARA",
      area: "Kepulauan Seribu",
      alamat: "Kel. Pulau Harapan ",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan KEPULAUAN SERIBU SELATAN",
      area: "Kepulauan Seribu",
      alamat: "Pulau Tidung",
      contact: "",
    },
    { name: " ", area: "", alamat: "", contact: "" },
    {
      name: "Puskesmas Kelurahan KEPULAUAN SERIBU SELATAN",
      area: "Kepulauan Seribu",
      alamat: "Kel Pulau Untung Jawa",
      contact: "021-70617381",
    },
    {
      name: "Puskesmas Kelurahan KEPULAUAN SERIBU SELATAN",
      area: "Kepulauan Seribu",
      alamat: "Kel. Pulau Pari021-70978166",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Moh Kahfi RT 009",
      contact: "021-7864707",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Jagakarsa RT 004",
      contact: "021-7873926",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Jati Padang Raya. RT 012",
      contact: "021-7874051",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Lontar RT 009",
      contact: "021-7875322",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Gang Subur RT 010",
      contact: "021-7875307",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Baru",
      contact: "021-7874051",
    },
    {
      name: "Puskesmas Kelurahan JAGAKARSA",
      area: "Jakarta Selatan",
      alamat: "Jl. Moh. Kahfi RT 009 (STATUS KONTRAK BANGUNAN)",
      contact: "0-0",
    },
    {
      name: "Puskesmas Kecamatan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Raya Jati Padang",
      contact: '""021-7811265',
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Swadaya I/28 RT 006/11",
      contact: "021-78012870",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Pejaten Raya No. 3",
      contact: "021-7949636",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Ayub Gg F RT 002/02",
      contact: "021-7949982",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Siaga Raya BAPPENAS",
      contact: "021-7943777",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. BII Rawa Bambu (KOMP. AL)",
      contact: "021-7829927",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Raya Ragunan",
      contact: "021-7891734",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Puskesmas RT 008/02",
      contact: "021-7803117",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Harsono RM RT 007/02",
      contact: "021-7812770",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Madrasah No. 11 RT 10/05",
      contact: "021-7814555",
    },
    {
      name: "Puskesmas Kelurahan PASAR MINGGU",
      area: "Jakarta Selatan",
      alamat: "Jl. Jati Padang 1A",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Komplek BNI 1946",
      contact: '""021-7661613',
    },
    {
      name: "Puskesmas Kelurahan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Madrasah 25",
      contact: "012-7650437",
    },
    {
      name: "Puskesmas Kelurahan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Anggur II RT 016",
      contact: "021-7669455",
    },
    {
      name: "Puskesmas Kelurahan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Sekura 123",
      contact: "021-7663586",
    },
    {
      name: "Puskesmas Kelurahan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Puskesmas RT 001/06",
      contact: "021-7665710",
    },
    {
      name: "Puskesmas Kelurahan CILANDAK",
      area: "Jakarta Selatan",
      alamat: "Jl. Kelurahan Lama No. 2",
      contact: "021-7669456",
    },
    {
      name: "Puskesmas Kecamatan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Cenek Raya",
      contact: "021-7356087",
    },
    {
      name: "Puskesmas Kelurahan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Masjid Darul Falah",
      contact: "021-5866379",
    },
    {
      name: "Puskesmas Kelurahan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Kemajuan RT 008",
      contact: "021-7378180",
    },
    {
      name: "Puskesmas Kelurahan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Ulujami Raya 18",
      contact: "021-7377862",
    },
    {
      name: "Puskesmas Kelurahan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Mufakat RT 002",
      contact: "021-7356807",
    },
    {
      name: "Puskesmas Kelurahan PESANGGRAHAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Wijaya Kusuma",
      contact: "021-73880174",
    },
    {
      name: "Puskesmas Kecamatan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Ciputat Raya RT 005",
      contact: "021-7245439",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Kemandoran I RT 006",
      contact: "021-5324826",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Tanah Baru  V",
      contact: "021-5324968",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Kuburan Islam RT 011",
      contact: "021-7224909",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Cileduk Raya Gg Indra",
      contact: "021-7257810",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Kebon Mangga II/30",
      contact: "021-7269603",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Bendi Raya Blok A",
      contact: "021-7238750",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Bungur",
      contact: "021-7248428",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN LAMA",
      area: "Jakarta Selatan",
      alamat: "Jl. Ciputat Raya",
      contact: "021-7651435",
    },
    {
      name: "Puskesmas Kecamatan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Iskandarsyah Raya 106",
      contact: "021-7220274",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Tulodong Bawah  V",
      contact: "021-5271405",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Gunawarman 74",
      contact: "021-7205570",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Rajasa  III/4",
      contact: "021-7236636",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Bone No. 25",
      contact: "021-7258548",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: '""Jl. Gandaria Tengah',
      contact: '  V/3""',
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Pulo Raya",
      contact: "021-7262979",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Bayem  I/4",
      contact: "021-7244166",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Deltasari  F/10",
      contact: "021-7228612",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. Masjid Blok A",
      contact: "021-7223458",
    },
    {
      name: "Puskesmas Kelurahan KEBAYORAN BARU",
      area: "Jakarta Selatan",
      alamat: "Jl. H Abd Majid",
      contact: "021-7237462",
    },
    {
      name: "Puskesmas Kecamatan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Kapt. Tendean RT. 011",
      contact: "021-79192187",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Poncol Jaya  No. 40",
      contact: "021-5260944",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Buncit Ujung RT. 012",
      contact: "021-7943509",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Pondok Jaya  III",
      contact: "021-7194008",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Bangka Gg  V RT. 008",
      contact: "021-7194967",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Mampang Prapatan XI",
      contact: "021-7941580",
    },
    {
      name: "Puskesmas Kelurahan MAMPANG PRAPATAN",
      area: "Jakarta Selatan",
      alamat: "Jl. SD Bangka No. 2",
      contact: "021-7196578",
    },
    {
      name: "Puskesmas Kecamatan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Potlot II  RT. 002",
      contact: "021-7974024",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Binawarga RT. 003",
      contact: "021-7944040",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Megawai Raya VII  RT. 012",
      contact: "021-7446642",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Warung Jati  VII",
      contact: "021-79198514",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Cikoto  RT. 003",
      contact: "021-7946051",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Jl. Pengadegan Timur RT. 003",
      contact: "021-7946050",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Kel. Pancoran",
      contact: "021-7980483",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Kel. Rawajati",
      contact: "021-7946634",
    },
    {
      name: "Puskesmas Kelurahan PANCORAN",
      area: "Jakarta Selatan",
      alamat: "Kel. Rawajati",
      contact: "021-7988538",
    },
    {
      name: "Puskesmas Kecamatan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Prof. Supomo No. 54",
      contact: "021-8314955",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Warung Pedok  II RT. 003",
      contact: "021-8352943",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Tebet Timur  III",
      contact: "021-8295976",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Asem Baris Raya No. 65",
      contact: "021-8350632",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Bukit Duri Tanjakan",
      contact: "021-8353524",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Dr Saharjo Gg Rambutan",
      contact: "021-8352556",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Dr Saharjo Gg Bedeng Dalam",
      contact: "021-8352992",
    },
    {
      name: "Puskesmas Kelurahan TEBET",
      area: "Jakarta Selatan",
      alamat: "Jl. Dr Saharjo Gg Bedeng Dalam",
      contact: "021-8305391",
    },
    {
      name: "Puskesmas Kecamatan SETIA BUDI",
      area: "Jakarta Selatan",
      alamat: "Jl. Halimun No. 14",
      contact: "021-8295529",
    },
    {
      name: "Puskesmas Kelurahan SETIA BUDI",
      area: "Jakarta Selatan",
      alamat: "Jl. Jend. Sudirman No.13A",
      contact: "021-5263352",
    },
    {
      name: "Puskesmas Kelurahan SETIA BUDI",
      area: "Jakarta Selatan",
      alamat: "Jl. Karet Belakang RT. 011",
      contact: "021-5264352",
    },
    {
      name: "Puskesmas Kelurahan SETIA BUDI",
      area: "Jakarta Selatan",
      alamat: "Jl. Menteng Granit  4",
      contact: "021-8308588",
    },
    {
      name: "Puskesmas Kelurahan SETIA BUDI",
      area: "Jakarta Selatan",
      alamat: "Jl. Subur Komplek AKABRI",
      contact: "021-8305394",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "",
      alamat: "",
      contact: "Kontrak tahun 2013",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "",
      alamat: "",
      contact: "Kontrak tahun 2013",
    },
    {
      name: "Puskesmas Kecamatan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Lapan Kalisari No 1 RT. 010/01",
      contact: "021-8720053",
    },
    {
      name: "Puskesmas Kelurahan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Puskesmas Kel. Baru RT. 008/01",
      contact: "021-87780576",
    },
    {
      name: "Puskesmas Kelurahan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Condet RT. 012/03",
      contact: "021-8413140",
    },
    {
      name: "Puskesmas Kelurahan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Pertengahan Kel. Cijantung 05/07",
      contact: "021-8705354",
    },
    {
      name: "Puskesmas Kelurahan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Puskesmas Kel. Kalisari RT. 003/03",
      contact: "021-8708609",
    },
    {
      name: "Puskesmas Kelurahan PASAR REBO",
      area: "Jakarta Timur",
      alamat: "Jl. Bulak Sari RT. 009/06",
      contact: "021-8718480",
    },
    {
      name: "Puskesmas Kecamatan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Lapang Tembak RT. 003/01",
      contact: "021-8718995",
    },
    {
      name: "Puskesmas Kelurahan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. H. Jenih Rt 012/01",
      contact: "021-87781628",
    },
    {
      name: "Puskesmas Kelurahan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Cantex Rt 012/02",
      contact: "021-8708800",
    },
    {
      name: "Puskesmas Kelurahan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Mesjid Rt 010/04 Bulak Sereh",
      contact: "021-87711043",
    },
    {
      name: "Puskesmas Kelurahan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. H. Baping Rt 009/06",
      contact: "021-8406584",
    },
    {
      name: "Puskesmas Kelurahan CIRACAS",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Kelapa Dua Wetan Rt 001/06",
      contact: "021-70981100",
    },
    {
      name: "Puskesmas Kecamatan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Monumen Pancasila Sakti Rt 002/02",
      contact: "021-87792277",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Monumen Pancasila",
      contact: "021-87793082",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Mini II Rt 002/03",
      contact: "021-84975368",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Shinta Raya",
      contact: "021-84995372",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Prapatan Kincir",
      contact: "021-84593943",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Dalang Rt 012/02",
      contact: "021-8454964",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Puskesmas Rt 001/03",
      contact: "021-84597466",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Puskesmas No 16 Rt 004/03",
      contact: "021-84594524",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Sepakat V",
      contact: "021-8454784",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Kramat gancang Rt 001/04",
      contact: "021-8457548",
    },
    {
      name: "Puskesmas Kelurahan CIPAYUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Komp Buperta Rt 001/03 Munjul",
      contact: "021-84594012",
    },
    {
      name: "Puskesmas Kecamatan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Pusdiklat DEPNAKER No. 37",
      contact: "021-8003308",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Budi Harapan II",
      contact: "021-86609575",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Permadi Dirgantara I",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Halim Golf",
      contact: "021-80886841",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Cakrawala Rt.006/10",
      contact: "021-8007620",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Pondok Gede",
      contact: "021-87797347",
    },
    {
      name: "Puskesmas Kelurahan MAKASAR",
      area: "Jakarta Timur",
      alamat: "Jl. Karya Bhakti Rt.013/02",
      contact: "021-8003533",
    },
    {
      name: "Puskesmas Kecamatan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Inpres No.48 Kel Tengah",
      contact: "021-87791352",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Mesjid Bendungan I Rt 009/10",
      contact: "021-8091870",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Ciliwung Buluh Rt 005/16",
      contact: "021-80889974",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Langgar Rt 006/10",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. RS Polri Rt 006/04",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Batu Ampar II Wadas Rt 008/03",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Gardu Rt 001/02",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Murai Rt 002/02",
      contact: "021-87780057",
    },
    {
      name: "Puskesmas Kelurahan KRAMAT JATI",
      area: "Jakarta Timur",
      alamat: "Jl. Kelurahan Rt 010/04",
      contact: "021-70921124",
    },
    {
      name: "Puskesmas Kecamatan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Matraman Raya 220",
      contact: "021-8195146",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Kebon Pala 1/32",
      contact: "021-8515004",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Wedana 006/02",
      contact: "021-85908911",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Otto Iskandar Dinata 82 Rt 006/06",
      contact: "021-85903677",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Nilam Kp. Dalam Rt 0013/011",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Tanjung Lengkong Rt 017/07",
      contact: "021-85917587",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Cipinang Cempedak IV Rt 011/06",
      contact: "021-85909474",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Jatinegara Timur IV Rt 02/07",
      contact: "021-8511689",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. BB I Rt 06/15 Cipinang Muara",
      contact: "021-85907746",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Cipinang Pulo Maja Rt 0015/11",
      contact: "021-8513945",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Cipinang Jaya FF Rt 001/07",
      contact: "021-8511127",
    },
    {
      name: "Puskesmas Kelurahan JATINEGARA",
      area: "Jakarta Timur",
      alamat: "Jl. Pancawarga IV/4",
      contact: "021-85909549",
    },
    {
      name: "Puskesmas Kecamatan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. H. Dogol (samping SMUN 71)",
      contact: "021-86601065",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Kesehatan 5 Rt 002/05",
      contact: "021-70990050",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Cipinang Muara II",
      contact: "021-8615989",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Pertanian Timur Rt 003/02",
      contact: "021-86605147",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Bulak Timur I No. 8 Rt 004/16",
      contact: "021-86603350",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Taman Buaran Indah 2",
      contact: "021-9199605",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Kelurahan Raya Rt 005/02",
      contact: "021-86602052",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Teratai Putih No. 1",
      contact: "021-86608372",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Malaka III Rt 001/06",
      contact: "021-68299711",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Bina Karya Rawa Wadas Rt 003/06",
      contact: "021-86904054",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Robusta Raya Blok Q VIII",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan DUREN SAWIT",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Pondok Kelapa Rt 0010/04",
      contact: "021-86903157",
    },
    {
      name: "Puskesmas Kecamatan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Bekasi Km 18",
      contact: "021-4608446",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Bekasi Km 14",
      contact: "021-46829720",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Bekasi Km 17 Rt 005/03",
      contact: "021-4612345",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Komp PIK",
      contact: "021-4807827",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Komp. Aneka Elok Jl. Mentibu Rt 12",
      contact: "021-46829710",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Balai Rakyat Rt 0013/01",
      contact: "021-46829810",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Tipar Rt 001/07",
      contact: "021-46829709",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Raya Bekasi",
      contact: "021-46828217",
    },
    {
      name: "Puskesmas Kelurahan CAKUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Stasiun Km 4 Rt 006/03",
      contact: "021-4807828",
    },
    {
      name: "Puskesmas Kecamatan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Kayu Putih Selatan III13210",
      contact: "021-4890519",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Plapon I Rt 002/01",
      contact: "021-4710423",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Pulo Asem Rt 001/02",
      contact: "021-47868535",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Kaplongan I/267",
      contact: "021-47868404",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. Taman Jeruk",
      contact: "021-47864411",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. H Nugni III Rt 0012/04",
      contact: "021-4755612",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Kel. Pisangan Timur",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. El Cipinang/Masjid Baitussalam No.19",
      contact: "021-4756139",
    },
    {
      name: "Puskesmas Kelurahan PULO GADUNG",
      area: "Jakarta Timur",
      alamat: "Jl. TB Badarudin Rt 15/07",
      contact: "021-4755580",
    },
    {
      name: "Puskesmas Kecamatan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Kebon Kelapa Raya 29 B",
      contact: "021-8581957",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Kayu Manis II",
      contact: "021-8513170",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Pegayoman Komp. Kehakiman",
      contact: "021-85900050",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Kebun Sereh BRI Rt 003/09",
      contact: "021-8507756",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Skip Ujung Rt 004/07",
      contact: "021-8511129",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Jl. Palmeriem",
      contact: "021-85909517",
    },
    {
      name: "Puskesmas Kelurahan MATRAMAN",
      area: "Jakarta Timur",
      alamat: "Kel. Utan Kayu Selatan",
      contact: "021-8512337",
    },
    {
      name: "Puskesmas Kecamatan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. KH. Mas Mansyur No. 30 RT 05/07",
      contact: "021-3150427",
    },
    {
      name: "Puskesmas Kelurahan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. Kamp Bali Gg. 23 RT. 07/07",
      contact: "021-3015071",
    },
    {
      name: "Puskesmas Kelurahan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. Petamburan IV RT. 012/04",
      contact: "021-53650696",
    },
    {
      name: "Puskesmas Kelurahan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. Karet Pasar Baru Barat VII/19 RT. 09/02",
      contact: "021-5743287",
    },
    {
      name: "Puskesmas Kelurahan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. Danau Toba Blok A No. 1 RT. 020/04",
      contact: "021-5732767",
    },
    {
      name: "Puskesmas Kelurahan TANAH ABANG",
      area: "Jakarta Pusat",
      alamat: "Jl. Lapangan Tembak Senayan",
      contact: "021-5743355",
    },
    {
      name: "Puskesmas Kecamatan MENTENG",
      area: "Jakarta Pusat",
      alamat: "Jl. Pegangsaan Barat No. 14 RT. 16/05",
      contact: "021-31935836",
    },
    {
      name: "Puskesmas Kelurahan MENTENG",
      area: "Jakarta Pusat",
      alamat: "Jl. Sumatra No. 50 RT. 02/04",
      contact: "021-31934421",
    },
    {
      name: "Puskesmas Kelurahan MENTENG",
      area: "Jakarta Pusat",
      alamat: "Jl. Tambak No. 28",
      contact: "021-31934355",
    },
    {
      name: "Puskesmas Kecamatan SENEN",
      area: "Jakarta Pusat",
      alamat: "Jl. Kramat VII",
      contact: "021-3146194",
    },
    {
      name: "Puskesmas Kelurahan SENEN",
      area: "Jakarta Pusat",
      alamat: "Jl. Jambrut No. 22 RT. 07/02",
      contact: "021-31923932",
    },
    {
      name: "Puskesmas Kelurahan SENEN",
      area: "Jakarta Pusat",
      alamat: "Jl. Kramat Sentiong Ujung I/33",
      contact: "021-3919683",
    },
    {
      name: "Puskesmas Kelurahan SENEN",
      area: "Jakarta Pusat",
      alamat: "Kel. Bungur",
      contact: "021-4215473",
    },
    {
      name: "Puskesmas Kelurahan SENEN",
      area: "Jakarta Pusat",
      alamat: "Jl. Kramat Sawah VII RT.008/07",
      contact: "021-3913927",
    },
    {
      name: "Puskesmas Kelurahan SENEN",
      area: "Jakarta Pusat",
      alamat: "Jl. Kwitang IC",
      contact: "021-3146238",
    },
    {
      name: "Puskesmas Kecamatan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Tanah Tinggi XII RT. 004/09",
      contact: "021-4246359",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Tanah Tinggi VII RT. 006/06",
      contact: "021-4229105",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Mardani Raya No. 36 RT. 02/05",
      contact: "021-4256443",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Percetakan Negara II RT. 011/06",
      contact: "021-4229102",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Kramat Raya Baru Gg IX RT. 013/01",
      contact: "021-4219544",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Rawa Tengah IX RT.011/06",
      contact: "021-4256442",
    },
    {
      name: "Puskesmas Kelurahan JOHAR BARU",
      area: "Jakarta Pusat",
      alamat: "Jl. Rawa Selatan I RT. 011/04",
      contact: "021-4256445",
    },
    {
      name: "Puskesmas Kecamatan CEMPAKA PUTIH",
      area: "Jakarta Pusat",
      alamat: "Jl. Rawasari Selatan RT. 014/02",
      contact: "021-4219548",
    },
    {
      name: "Puskesmas Kelurahan CEMPAKA PUTIH",
      area: "Jakarta Pusat",
      alamat: "Jl. Pramuka Sari I",
      contact: "021-4256428",
    },
    {
      name: "Puskesmas Kelurahan CEMPAKA PUTIH",
      area: "Jakarta Pusat",
      alamat: "Jl. Percetakan Negara D 685",
      contact: "021-4243793",
    },
    {
      name: "Puskesmas Kelurahan CEMPAKA PUTIH",
      area: "Jakarta Pusat",
      alamat: "Jl. Cempaka Putih Barat II D/10A",
      contact: "021-4250858",
    },
    {
      name: "Puskesmas Kecamatan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Serdang Baru I RT. 006/05",
      contact: "021-42801847",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Pelita 3 RT. 008/08",
      contact: "021-4229104",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Kemayoran Gempol 28 RT. 06/06L",
      contact: "021-42802057",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Eka 5 RT. 09/03",
      contact: "021-4256429",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Bendungan Jago RT. 09/01",
      contact: "021-4250857",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Harapan Mulya RT. 04/05",
      contact: "021-4220947",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Cempaka Baru Tengah I RT. 05/06",
      contact: "021-4220193",
    },
    {
      name: "Puskesmas Kelurahan KEMAYORAN",
      area: "Jakarta Pusat",
      alamat: "Jl. Sumur Batu Raya RT. 07/01",
      contact: "021-4222510",
    },
    {
      name: "Puskesmas Kecamatan SAWAH BESAR",
      area: "Jakarta Pusat",
      alamat: "Jl. Dwi Warna 6/7",
      contact: "021-6298090 - 6283864",
    },
    {
      name: "Puskesmas Kelurahan SAWAH BESAR",
      area: "Jakarta Pusat",
      alamat: "Jl. Mangga Dua Dalam 12 RT. 01/10",
      contact: "021-6256101",
    },
    {
      name: "Puskesmas Kelurahan SAWAH BESAR",
      area: "Jakarta Pusat",
      alamat: "Jl. Krekot Bunda Raya No. 10",
      contact: "021-3440087",
    },
    {
      name: "Puskesmas Kelurahan SAWAH BESAR",
      area: "Jakarta Pusat",
      alamat: "Jl. Kartini 8 Dalam",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan GAMBIR",
      area: "Jakarta Pusat",
      alamat: "Jl. Tanah Abang I/10",
      contact: "021-3810051",
    },
    {
      name: "Puskesmas Kelurahan GAMBIR",
      area: "Jakarta Pusat",
      alamat: "Jl. Petojo Selatan 2",
      contact: "021-",
    },
    {
      name: "Puskesmas Kelurahan GAMBIR",
      area: "Jakarta Pusat",
      alamat: "Jl. Petojo Selatan II RT. 02/04",
      contact: "021-6338341",
    },
    {
      name: "Puskesmas Kelurahan GAMBIR",
      area: "Jakarta Pusat",
      alamat: "Jl. Taman Tanah Abang III",
      contact: "021-3520246",
    },
    {
      name: "Puskesmas Kelurahan GAMBIR",
      area: "Jakarta Pusat",
      alamat: "Jl. Batu Tulis 13 No.1",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Komp. Taman Meruya Ilir Blok F/3",
      contact: "021-5870834",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Kembangan Rt 005/02",
      contact: "021-68534570",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "021-5843136",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Meruya Selatan",
      contact: "021-68534571",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. H. Saaba Komp Walikota Jak-Bar",
      contact: "021-5859081",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Komp. Perumahan DKI Joglo",
      contact: "021-5840451",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Joglo",
      contact: "021-58902737",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Srengseng",
      contact: "021-68534572",
    },
    {
      name: "Puskesmas Kelurahan KEMBANGAN",
      area: "Jakarta Barat",
      alamat: "Jl. Manggis Rt.005/07 ",
      contact: "021-70642117",
    },
    {
      name: "Puskesmas Kecamatan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Kebon Jeruk No. 2 Rt.09/01",
      contact: "021-5482367",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Kedoya Raya Rt.004/03",
      contact: "021-58303182",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Angsana Raya No. 1",
      contact: "021-56944087",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Karmel Raya Rt. 002/04",
      contact: "021-53679240",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Sukabumi Sel Rt.008/03",
      contact: "021-5361034",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Harum Raya Rt.008/07",
      contact: "021-5362526",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Sasak I Rt.001/002",
      contact: "021-5301349",
    },
    {
      name: "Puskesmas Kelurahan KEBON JERUK",
      area: "Jakarta Barat",
      alamat: "Jl. Daan Mogot Pesing Rt.003/02",
      contact: "021-56943877",
    },
    {
      name: "Puskesmas Kecamatan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Palmerah 120",
      contact: "021-5483693",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Waru No. 1 A",
      contact: "021-56940307",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Semangka Rt. 006/07",
      contact: "021-56940316",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. KS Tubun I/27",
      contact: "021-56940315",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Pondok Bandung",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. KS Tubun II",
      contact: "021-5323118",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. KS Tubun IV No. 140",
      contact: "021-5306265",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Kemanggisan Pulo Rt. 012/03",
      contact: "021-5347484",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Rawa Belong No. 11 E",
      contact: "021-5347336",
    },
    {
      name: "Puskesmas Kelurahan PALMERAH",
      area: "Jakarta Barat",
      alamat: "Jl. Anggrek Garuda D/4",
      contact: "021-5306368",
    },
    {
      name: "Puskesmas Kecamatan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Wijaya VIII Duta Mas",
      contact: "021-5648379",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Dr. Nurdin I/35",
      contact: "021-56943089",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Rawa Bahagia I/32",
      contact: "021-56971251",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Dr. Nurdin Raya",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Satria II Rt 004/04",
      contact: "021-56941881",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Prof DR. Latumenten No.VI/2",
      contact: "021-56975053",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Jelembar Ilir",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Tanjung Duren 120",
      contact: "021-56941907",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Tanjung Duren VII B",
      contact: "021-5641241",
    },
    {
      name: "Puskesmas Kelurahan GROGOL PETAMBURAN",
      area: "Jakarta Barat",
      alamat: "Jl. Tomang Pulo Macam V/40",
      contact: "021-5603976",
    },
    {
      name: "Puskesmas Kecamatan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Krendang Utara No. 4",
      contact: "021-6313651",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Bandengan Utara No. 4",
      contact: "021-6906376",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Kampung Janis No. 5",
      contact: "021-913719",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Tiang Bendera Selatan",
      contact: "021-6929267",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Tambora I No. 6",
      contact: "021-6319774",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Angke Indah Gg.VII",
      contact: "021-6347870",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Duri Baru Rt.oo4/04",
      contact: "021-6301501",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Duri Utara II/23",
      contact: "021-6301972",
    },
    {
      name: "Puskesmas Kelurahan TAMBORA",
      area: "Jakarta Barat",
      alamat: "Jl. Persima II No. 10",
      contact: "021-6314812",
    },
    {
      name: "Puskesmas Kecamatan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Madu No. 10",
      contact: "021-6297752",
    },
    {
      name: "Puskesmas Kelurahan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Blustru No. 16",
      contact: "021-6595342",
    },
    {
      name: "Puskesmas Kelurahan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Kebon Sayur I No.6",
      contact: "021-6313624",
    },
    {
      name: "Puskesmas Kelurahan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Krutut Lio",
      contact: "021-6319817",
    },
    {
      name: "Puskesmas Kelurahan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Kebon Jeruk X",
      contact: "021-6592603",
    },
    {
      name: "Puskesmas Kelurahan TAMAN SARI",
      area: "Jakarta Barat",
      alamat: "Jl. Mangga Besar XIII",
      contact: "021-6247319",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "",
      alamat: "",
      contact: "Kontrak Tahun 2013",
    },
    {
      name: "Puskesmas Kecamatan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Kamal Raya",
      contact: "021-54398366",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Bojong Raya Rt 002/04",
      contact: "021-58300444",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Nurul Amal Rt 013/04",
      contact: "021-70601473",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Flamboyan No. 75",
      contact: "021-55960714",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Cendrawasih VII",
      contact: "021-54371828",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Kapuk Rt003/11",
      contact: "021-70601471",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Kapuk Rt004/05",
      contact: "021-70601472",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Komp. Depag Kaliangke",
      contact: "021-54366208",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Duri Kosambi I",
      contact: "021-5459413",
    },
    {
      name: "Puskesmas Kelurahan CENGKARENG",
      area: "Jakarta Barat",
      alamat: "Jl. Raya Rawa Buaya 04/07",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Satu Maret",
      contact: "021-54390576",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "JL. Raya Semanan No. 37",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Semanan Raya Rt 005/03",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Kebon 200 Rt 007/01",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Sukatani Rt 007/02",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Komp. Kebersihan Rt 007/04",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Kayu Besar Rt 006/12",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Wadas Rt 002/06",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Tanjung Pura Rt 006/05",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Kumbang Raya",
      contact: "021-5443023",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Komp. Citra Garden Blok M",
      contact: "021-54392924",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Peta Selatan Rt 007/01",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KALI DERES",
      area: "Jakarta Barat",
      alamat: "Jl. Kp. Belakang",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Telok Gong Raya No.2",
      contact: "021-6694917",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Kamal Muara Raya",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. SMP 122",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Kura Telok Gong",
      contact: "021-6616245",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Pluit Raya Selatan No.2",
      contact: "021-66696374",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Pasar Royal",
      contact: "021-66696407",
    },
    {
      name: "Puskesmas Kelurahan PENJARINGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Muara Angke",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan PADEMANGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Budi Mulya No.11",
      contact: "021-6406609",
    },
    {
      name: "Puskesmas Kelurahan PADEMANGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Ancol Barat IV",
      contact: "021-6926483",
    },
    {
      name: "Puskesmas Kelurahan PADEMANGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Ampera Raya",
      contact: "021-6411276",
    },
    {
      name: "Puskesmas Kelurahan PADEMANGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Waspada Raya Gg. B2",
      contact: "021-6406246",
    },
    {
      name: "Puskesmas Kelurahan PADEMANGAN",
      area: "Jakarta Utara",
      alamat: "Jl. Pademangan II Gg. 22/2",
      contact: "021-64710433",
    },
    {
      name: "Puskesmas Kecamatan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Bugis No.63",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Bambu Kuning Gg. II / I",
      contact: "021-6517476",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Komplek Kebersihan DKI",
      contact: "021-6515132",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Papanggi II/ B N69",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Sungai Bambu IV/24",
      contact: "021-43905280",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Swasembada Barat VII",
      contact: "021-43905326",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Swasembada Barat IV",
      contact: "021-43905316",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Swasembada Barat II",
      contact: "021-43913350",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Kampung Bahari III/65",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Bambu Kuning Gg. II 1",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Agung Barat XXV",
      contact: "021-65833297",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Taman Nyiur Komp. Bl",
      contact: "021-6503209",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Warakas IX/22",
      contact: "021-4308865",
    },
    {
      name: "Puskesmas Kelurahan TANJUNG PRIOK",
      area: "Jakarta Utara",
      alamat: "Jl. Bisma Timur II",
      contact: "021-65832994",
    },
    {
      name: "Puskesmas Kecamatan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Walang Permai No. 39",
      contact: "021-4367168",
    },
    {
      name: "Puskesmas Kelurahan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Deli Gg. 28 No.2",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Mangga No.1",
      contact: "021-4302114",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "021-4403913",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Mahoni Selatan No.1",
      contact: "021-43905753",
    },
    {
      name: "Puskesmas Kelurahan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Bendungan Melayu Selatan Rt 001/05",
      contact: "021-43908519",
    },
    {
      name: "Puskesmas Kelurahan 021-43933827",
      area: "Jl. Rawa Badak Barat No. 37",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KOJA",
      area: "Jakarta Utara",
      alamat: "Jl. Rawa Binangun I",
      contact: "021-43908520",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "Jl. K-II No.7 Rt.009/005 Plumpang",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kecamatan KELAPA GADING",
      area: "Jakarta Utara",
      alamat: "Jl. Pelepah Raya",
      contact: "021-45853300",
    },
    {
      name: "Puskesmas Kelurahan 021-70792196",
      area: "Jl. Puskesmas No.9",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "Jl. Merah Jambu Blok EJ/22",
      alamat: "",
      contact: "",
    },
    {
      name: "Puskesmas Kelurahan KELAPA GADING",
      area: "Jakarta Utara",
      alamat: "Jl. H. Oyar",
      contact: "021-4618764",
    },
    {
      name: "Puskesmas Kelurahan KELAPA GADING",
      area: "Jakarta Utara",
      alamat: "Jl. Gadang No.1",
      contact: "021-4513321",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "",
      alamat: "",
      contact: "Kontrak Tahun 2013",
    },
    {
      name: "Puskesmas Kecamatan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Madya Kebantenan IV",
      contact: "021-4412889",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Kalibaru Timur 1/60",
      contact: "021-44835305",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Pasar Pagi No.11A",
      contact: "021-4416419",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Sungai Landak No.26",
      contact: "021-4404703",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Durian No.49",
      contact: "021-4400351",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Tipar Cakung No. 18",
      contact: "021-4410227",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Pepaya V",
      contact: "021-44835008",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Marunda Baru No.5",
      contact: "021-44852585",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Tipar Cakung",
      contact: "021-44834952",
    },
    {
      name: "Puskesmas Kelurahan CILINCING",
      area: "Jakarta Utara",
      alamat: "Jl. Manunggal Juang XIX No.4",
      contact: "021-44850175",
    },
    {
      name: "Puskesmas Kelurahan ",
      area: "",
      alamat: "",
      contact: "Kontrak Tahun 2013",
    },
  ];
  let databaseSurabaya = [
    [
      1,
      "Asemrowo",
      "dr. Diah Miryati",
      "Jln. Asem Raya No. 8",
      "(031) 5456122",
    ],
    [
      2,
      "Balas Klumprik",
      "dr. Yessy Pebriaty Sukatendel. MM",
      "Jln. Raya Balas Klumprik",
      "(031)7665219",
    ],
    [
      3,
      "Balongsari",
      "dr. Dewi Ayuning Asih",
      "Jln. Balongsari Tama No. 2 Surabaya",
      "(031) 7417104",
    ],
    [
      4,
      "Bangkingan",
      "dr. Winartuti Santoso, M.Kes",
      "Jln. Banyu Urip Kidul 6/8",
      "(031) 5685424",
    ],
    [
      5,
      "Banyu Urip",
      "dr. Aloysius Tri Joehanto, MH",
      "Jln. Raya Benowo No. 48",
      "(031) 7405936",
    ],
    [
      6,
      "Benowo",
      "dr. Aloysius Tri Joehanto",
      "MH	Jln. Raya Benowo No. 48",
      "(031) 7405936",
    ],
    [
      7,
      "Bulak Banteng",
      "drg. Elfi Asriningdiah Poedji Utami",
      "Jln. Dukuh Bulak Banteng Perintis Utama Lebar No.35",
      "(031) 3765209",
    ],
    [
      8,
      "Dr. Soetomo",
      "dr. Murtiningrum",
      "Jln. Pandegiling No.223-A",
      "081334932059",
    ],
    [
      9,
      "Dukuh Kupang",
      "dr. Khusnul Khowatin",
      "Jln. Dukuh Kupang 25/48",
      "(031) 5677615",
    ],
    [
      10,
      "Dupak",
      "dr. RR. Endang Dwihastutiningsih",
      "Jln. Dupak Bangunrejo Gg Poliklinik No.6 Surabaya",
      "(031) 3531009",
    ],
    [
      11,
      "Gading",
      "dr. Dwiastuti Setyorini",
      "Jln. Kapas Lor 1 no 1 Surabaya",
      "(031) 3767736",
    ],
    [
      12,
      "Gayungan",
      "drg. Harijanti Judaningsih",
      "Jln. Gayungsari Barat 124",
      "(031) 8290043",
    ],
    [
      13,
      "Gundih",
      "dr. Tita Pusparini, M. Kes",
      "Jln. Margodadi 36 - 38 Surabaya",
      "(031) 5476275",
    ],
    [14, "Gunung Anyar"],
    [
      15,
      "Jagir",
      "dr. Dessy Jumiaty Setia",
      "Jln. Bendul Merisi No 1",
      "(031) 8416926",
    ],
    [
      16,
      "Jemursari",
      "drg. Siti Januarsih",
      "Jln. Jemursari Selatan IV/5",
      "(031)8414743",
    ],
    [
      17,
      "Jeruk",
      "drg. Harjanti",
      "Jln. Raya Menganti Jeruk 277A",
      "(031) 7521680",
    ],
    [
      18,
      "Kalijudan",
      "dr. Ageng Rusbaya",
      "Jln. Kalijudan No. 123",
      "(031) 3824566",
    ],
    [
      19,
      "Kalirungkut",
      "dr. Bernadetta Martini",
      "Jln. Rungkut Puskesmas No. 1",
      "(031) 87006689",
    ],
    [
      20,
      "Kebonsari",
      "dr. Reyner Meilaksana S.M.H.Kes",
      "Jln. Kebonsari Manunggal No. 30 - 31",
      "(031) 8294420",
    ],
  ];
  let vaksinId = [
    `vacc1`,
    `vacc2`,
    `vacc3`,
    `vacc4`,
    `vacc5`,
    `vacc6`,
    `vacc7`,
    `vacc8`,
  ];
  let vaksinNama = [
    `Polio`,
    `Dengue`,
    `Rotaro Virus`,
    `Influenza`,
    `Tifoid`,
    `HPV`,
    `Hepatitis A`,
    `Hepatitis B`,
  ];
  let objDb = {};
  for (const [noUrut, ...sisaArr] of databaseSurabaya) {
    if (sisaArr.length > 2 && sisaArr.length > 3) {
      if (!objDb[noUrut]) {
        objDb[noUrut] = {};
      }
      let [nama, pimpinan, lokasi, noTelp] = sisaArr;
      objDb[noUrut]["nama"] = nama;
      objDb[noUrut]["pimpinan"] = pimpinan;
      objDb[noUrut]["lokasi"] = lokasi;
      objDb[noUrut]["noTelp"] = noTelp;
    }
  }
  localStorage.setItem("jakartaArr", JSON.stringify(databaseJakarta));
  localStorage.setItem("vaksinId", JSON.stringify(vaksinId));
  localStorage.setItem("vaksinNama", JSON.stringify(vaksinNama));
  localStorage.setItem("surabayaArr", JSON.stringify(objDb));
}

export default storeDb;
